spring.application.name=LostFoundLocatorApplication
server.port=9595

#database config
spring.datasource.url=jdbc:mysql://localhost:3306/lostfounddb
spring.datasource.username=root
spring.datasource.password=Abdull@h#4ARK
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

